edition: 3.0.0
name: dota2-betting
access: default

vars:
  region: cn-hangzhou

resources:
  dota2-betting:
    component: fc3
    props:
      region: ${vars.region}
      functionName: dota2-betting
      runtime: python3.9
      code: ./function.zip
      handler: index.handler
      memorySize: 512
      timeout: 60
      triggers:
        - triggerName: httpTrigger
          triggerType: http
          triggerConfig:
            authType: anonymous
            methods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
